# Generated by Django 4.1.5 on 2023-02-08 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('client_status', models.CharField(choices=[('potential', 'Potential Customer'), ('customer', 'Customer')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('sales_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('contract_status', models.CharField(choices=[('negotiation', 'Contract in Negotiation'), ('signed', 'Contract is signed')], max_length=20)),
                ('amount_due', models.FloatField(blank=True)),
                ('payment_due_date', models.DateField(blank=True)),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='epicEvents.client')),
                ('sales_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event_status', models.CharField(choices=[('preparation', 'In Preparation'), ('ongoing', 'Ongoing'), ('finished', 'Finished')], max_length=20)),
                ('attendee_number', models.IntegerField(blank=True)),
                ('event_date', models.DateField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epicEvents.client')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epicEvents.contract')),
                ('support_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
