# Generated by Django 4.1.5 on 2023-02-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epicEvents", "0004_alter_eventstatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventstatus",
            name="status",
            field=models.CharField(
                choices=[("preparation", "In Preparation"), ("finished", "Finished")],
                max_length=20,
            ),
        ),
    ]
