# Generated by Django 4.1.5 on 2023-02-15 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epicEvents", "0005_alter_eventstatus_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_status",
        ),
    ]
