# Generated by Django 4.1.5 on 2023-02-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("epicEvents", "0006_remove_event_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="epicEvents.eventstatus",
            ),
        ),
    ]
