# Generated by Django 4.1.5 on 2023-03-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("epicEvents", "0009_alter_contract_amount_due_alter_contract_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendee_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_status",
            field=models.ForeignKey(
                default="1",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="epicEvents.eventstatus",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.CharField(max_length=500),
        ),
    ]
